DRAFT: Rabbitmq
le-phare/docker-stack pull request #24
Opened 2024-01-22 18:36 UTC by pierreboissinot

2024-04-29 13:51 UTC, pierreboissinot commented
@thislg pourrais-tu jeter un oeil stp ?

2024-04-29 14:31 UTC, thislg reviewed
J'ai juste un doute sur la nécessité d'avoir ça dans la stack / est-ce qu'on est obligé de mettre une version mineure aussi précise ? La 3.8 est EOL depuis environ 2 ans.

2024-05-02 07:03 UTC, pierreboissinot commented
@thislg 

> J'ai juste un doute sur la nécessité d'avoir ça dans la stack

Sur les projets IMAPROTECT c'est un service qui est autant partagé qu'une database relationnelle. A l'avenir nous devrions aussi utilisé davantage rabbitmq via symfony/messenger plutôt que Doctrine.

 > est-ce qu'on est obligé de mettre une version mineure aussi précise ? 

Oui, une mineure peut inclure des BC break pour les client librairies

> La 3.8 est EOL depuis environ 2 ans.

Oui, je l'ai déjà signalé au SI du client mais pour l'instant nous devons nous contraindre à cette version obsolète.

2024-05-02 07:07 UTC, afrancois-lephare commented
@thislg @pierreboissinot 
> Sur les projets IMAPROTECT c'est un service qui est autant partagé qu'une database relationnelle. A l'avenir nous devrions aussi utilisé davantage rabbitmq via symfony/messenger plutôt que Doctrine.

C'est en effet plus optimisé mais tout dépend du portefeuille du client au final

2024-05-02 07:14 UTC, thislg requested changes

2024-05-02 07:14 UTC, thislg commented on CHANGELOG.md
> +
```suggestion
```

2024-05-13 14:23 UTC, thislg approved these changes

2024-05-13 14:23 UTC, merged